export default function Disclaimer() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20 text-gray-200">
      <h1 className="text-3xl font-bold mb-6">Legal Disclaimer</h1>

      <p className="mb-4">
        LawHelpZone provides AI-generated legal information intended for
        educational and informational purposes only.
      </p>

      <p className="mb-4">
        The information provided by this platform does not constitute legal
        advice and should not be relied upon as a substitute for professional
        legal consultation with a qualified attorney.
      </p>

      <p className="mb-4">
        While we strive to provide accurate and up-to-date information, we make
        no guarantees regarding the completeness, reliability, or accuracy of
        the content generated by the AI system.
      </p>

      <p>
        By using this platform, you acknowledge that LawHelpZone and its
        developers are not responsible for any decisions or actions taken based
        on the information provided.
      </p>
    </div>
  );
}